#
# Don't forget to configure .env !
#

version: '3'

networks:
  network_pangio:
    driver: bridge
    ipam:
      config:
        - subnet: ${PANGIO_SUBNET}

services:
  # Stores ingested data
  pangio-db:
    container_name: pangio-db
    image: mariadb
    restart: unless-stopped
    networks:
      - network_pangio
    environment:
      TZ: ${PANGIO_TIMEZONE}
      PUID: ${PANGIO_UID}
      PGID: ${PANGIO_GID}
      MYSQL_USER: ${PANGIO_DB_USER}
      MYSQL_DATABASE: ${PANGIO_DB_NAME}
      MYSQL_PASSWORD: ${PANGIO_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PANGIO_DB_PASSWORD_ROOT}

  # Exfiltrates data over GSM
  pangio-sender:
    container_name: pangio-sender
    build:
      context: ./sender
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - network_pangio
    volumes:
      - ${PANGIO_PGP_FOLDER}:/pgp:ro
    devices:
      - /dev/hwrng:/dev/hwrng:rw
    environment:
      TZ: ${PANGIO_TIMEZONE}
      PUID: ${PANGIO_UID}
      PGID: ${PANGIO_GID}
      GSM_PORT: ${PANGIO_GSM_PORT}
      GSM_BAUDRATE: ${PANGIO_GSM_BAUDRATE}
      REMOTE_NUMBER: ${PANGIO_GSM_REMOTE_NUMBER}

  # Ingests data from sensors/devices
  pangio-ingest:
    container_name: pangio-ingest
    build:
      context: ./ingest
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - network_pangio
    environment:
      TZ: ${PANGIO_TIMEZONE}
      PUID: ${PANGIO_UID}
      PGID: ${PANGIO_GID}
      MYSQL_HOST: pangio-db
      MYSQL_USER: ${PANGIO_DB_USER}
      MYSQL_DATABASE: ${PANGIO_DB_NAME}
      MYSQL_PASSWORD: ${PANGIO_DB_PASSWORD}
      PANGIO_WAP_SNIFFING_INTERFACE: ${PANGIO_WAP_SNIFFING_INTERFACE}

  # Listens for incoming SMS
  pangio-listener:
    container_name: pangio-listener
    build:
      context: ./listener
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - network_pangio
    volumes:
      - ${PANGIO_PGP_FOLDER}:/pgp:ro
    devices:
      - /dev/hwrng:/dev/hwrng:rw
      - /dev/ttyUSB0:/dev/ttyUSB0:rw
    environment:
      TZ: ${PANGIO_TIMEZONE}
      PUID: ${PANGIO_UID}
      PGID: ${PANGIO_GID}
      GSM_PORT: ${PANGIO_GSM_PORT}
      GSM_BAUDRATE: ${PANGIO_GSM_BAUDRATE}
      REMOTE_NUMBER: ${PANGIO_GSM_REMOTE_NUMBER}